"""create streams and devices

Revision ID: 1615ba97ca26
Revises: 
Create Date: 2026-01-11 16:40:26.056468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1615ba97ca26'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('streams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('stream_code', sa.String(length=32), nullable=False),
    sa.Column('rtmp_url', sa.String(length=255), nullable=False),
    sa.Column('hls_url', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('streams')
    op.drop_table('devices')
    # ### end Alembic commands ###
