"""add missing fields to streams

Revision ID: 691a831975c0
Revises: 1615ba97ca26
Create Date: 2026-01-12 05:37:00.542496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '691a831975c0'
down_revision: Union[str, Sequence[str], None] = '1615ba97ca26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streams', sa.Column('streamer_device_id', sa.String(length=36), nullable=False))
    op.add_column('streams', sa.Column('started_at', sa.DateTime(), nullable=False))
    op.add_column('streams', sa.Column('ended_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_streams_streamer_device_id'), 'streams', ['streamer_device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_streams_streamer_device_id'), table_name='streams')
    op.drop_column('streams', 'ended_at')
    op.drop_column('streams', 'started_at')
    op.drop_column('streams', 'streamer_device_id')
    # ### end Alembic commands ###
